name: Terraform Deploy

on: 
  workflow_dispatch:
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: tfm setup
        uses: hashicorp/setup-terraform@v2
      - name: tfm init
        run: terraform init
      - name: tfm plan
        run: terraform plan -no-color